spring: # Spring configuration
    datasource: # Database connection
        url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres
        username: postgres.htvtxwvfcbscbtegopgl
        password: F4bric4Escuel4*
        hikari:
            schema: sitas
        driver-class-name: org.postgresql.Driver

    jpa: # JPA
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        show-sql: true

server:
    port: 8080
    servlet:
        context-path: /sitas